config/routes.rb
Rails.application.routes.draw do

  root 'session#login'

  get '/surveys/:id/take', to: 'surveys#take'
  patch '/surveys/:id/take', to: 'surveys#store'

  get 'surveys/results'

  resources :authors
  resources :surveys
  resources :answers

  get 'session/login'
  post 'session/login'

  get 'session/logout'
  post 'session/login'

  get 'session/signup'
  post 'session/signup'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :question_id, presence: true
  validates :text, presence: true

  belongs_to :question
  belongs_to :taker
end

app/models/author.rb
class Author < ActiveRecord::Base
  validates :name, presence: true
  validates :password_digest, presence: true

  has_secure_password
  has_many :surveys
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :order_number, presence: true
  validates :question_type, presence: true
  validates :text, presence: true

  belongs_to :survey
  has_many :answers

  accepts_nested_attributes_for :answers,
    reject_if: :all_blank,
    allow_destroy: true

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  validates :title, presence: true

  before_update :delete_marked_questions

  belongs_to :author
  has_many :questions
  has_many :answers, through: :questions
  has_many :takers, through: :answers
  # has_many :answers, through: :takers
  accepts_nested_attributes_for :questions,
    reject_if: :all_blank,
    allow_destroy: true

  accepts_nested_attributes_for :takers,
    reject_if: :all_blank,
    allow_destroy: true


  private def delete_marked_questions
    questions.to_a.delete_if { |q| q.destroy if q.obliterate == "1" }
  end

end

app/models/taker.rb
class Taker < ActiveRecord::Base
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def logged_in?
    redirect_to session_login_path, notice: "You must log in to access this page" unless session[:author_id]
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?
  skip_before_action :logged_in?, only: [:new, :create]
  # GET /authors
  def index
    @authors = Author.all
  end

  # GET /authors/1
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author, notice: 'Author was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /authors/1
  def update
    if @author.update(author_params)
      redirect_to @author, notice: 'Author was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /authors/1
  def destroy
    @author.destroy
    redirect_to authors_url, notice: 'Author was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
      redirect_to survey_path unless @author.id == session[:author_id]
    end

    # Only allow a trusted parameter "white list" through.
    def author_params
      params.require(:author).permit(:name, :password, :email, :phone, :address, :city, :state, :gender, :age, :image)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def login
    if !session[:author_id]
      author = Author.find_by_name(params[:name])
      if author && author.authenticate(params[:password])
        session[:author_id] = author.id
        session[:role] = "author"
        redirect_to surveys_path, notice: "You have succesfully logged in!"
      else
        if author
          flash.now[:alert] = "Login failed: invalid email or password."
        end
        render "login"
      end

    else
      redirect_to surveys_path
    end

  end

  def logout
    session[:author_id] = nil
    session[:role] = nil
    redirect_to session_login_path, notice: "See you next time!"
  end

  def signup
    redirect_to new_author_path

  end
end

#
#
# class SessionsController < ApplicationController
#
#   def new
#
#   end
#
#   def create
#     teacher = Teacher.find_by_email(params[:email])
#     if teacher && teacher.authenticate(params[:password])
#       session[:user_id] = teacher.id
#       session[:user_type] = "Teacher"
#
#       redirect_to root_path, notice: "You have succesfully logged in!"
#     else
#       flash.now[:alert] = "Login failed: invalid email or password."
#       render "new"
#     end
#   end
#
#   def destroy
#     session[:user_id] = nil
#     session[:user_type] = nil
#     redirect_to login_path, notice: "You have logged out."
#   end
#
# end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  before_action :set_take_survey, only: [:take, :store, :thankyou]
  before_action :logged_in?, except: [:take, :store, :thankyou]
  # skip_before_action :logged_in?, only: [:take, :store]

  # GET /surveys
  def index
    @surveys = Survey.where(author_id: session["author_id"])
  end

  # GET /surveys/1
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    @survey.questions.build
  end

  # GET /surveys/1/edit
  def edit
    @survey.questions.build

  end

  # POST /surveys
  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      redirect_to @survey, notice: 'Survey was successfully created.'
    else
      render :new
    end
  end

  def take
    @taker = Taker.create
  end

  def store
    survey = Survey.find(params[:id])

    if survey.update!(survey_params)
      survey.reload
      redirect_to answers_url, notice: "Thanks for completing the survey!"
    end
  end

  def thankyou
  end

  def results
    @survey = Survey.find(params[:id])
  end



  # PATCH/PUT /surveys/1
  def update
    p survey_params
    if @survey.update(survey_params)
      redirect_to @survey, notice: "Survey was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /surveys/1
  def destroy
    @survey.destroy
    redirect_to surveys_url, notice: 'Survey was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.where(id: params[:id]).first
      redirect_to surveys_url unless @survey != nil && @survey.author_id == session[:author_id]
    end

    def set_take_survey
      @survey = Survey.where(id: params[:id]).first

    end

    # Only allow a trusted parameter "white list" through.
    def survey_params
      params.require(:survey).permit(:title, :author_id, :description, :link ,questions_attributes: [:id, :order_number, :question_type, :text, :required, :obliterate, answers_attributes: [:id, :text, :taker_id]] )
    end



end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

Thanks for your time!

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="create-account-wrapper">
  <div class="create-account-box">
    <div class="create-account-box-intro">
      Please fill out the fields below. <br>  Starred fields are required to proceed.
    </div>
    <div class="create-account-labels">

  <div class="create-account-label">
    <%= f.label :name %><br>
      </div>
      <div class="create-account-input">
    <%= f.text_field :name %>
  </div>
  <div class="create-account-label">
    <%= f.label :password %><br>
      </div>
      <div class="create-account-input">
    <%= f.password_field :password %>
  </div>
  <div class="create-account-label">
    <%= f.label :email %><br>
      </div>
      <div class="create-account-input">
    <%= f.text_field :email %>
  </div>
  <div class="create-account-label">
    <%= f.label :phone %><br>
      </div>
      <div class="create-account-input">
    <%= f.text_field :phone %>
  </div>
  <div class="create-account-label">
    <%= f.label :address %><br>
      </div>
      <div class="create-account-input">
    <%= f.text_field :address %>
  </div>
  <div class="create-account-label">
    <%= f.label :city %><br>
      </div>
      <div class="create-account-input">
    <%= f.text_field :city %>
  </div>
  <div class="create-account-label">
    <%= f.label :state %><br>
      </div>
      <div class="create-account-input">
    <%= f.text_field :state %>
  </div>  <div class="create-account-label">
      <%= f.label :age %><br>
  </div>
  <div class="create-account-input">
      <%= f.text_field :age %>
    </div>
    <div class="create-account-label">
      <%= f.label :gender %><br>
        </div>
        <div class="create-account-input">
      <%= f.text_field :gender %>
    </div>  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

  </div>
</div>

app/views/authors/edit.html.erb
<!-- <h1>Editing Author</h1> -->

<%= render 'form' %>

<!-- <%= link_to 'Show', @author %> | -->
<!-- <%= link_to 'Back', author_path %> -->

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.password %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', session_signup_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @author.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @author.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @author.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @author.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @author.state %>
</p>

<p>
  <strong>Age:</strong>
  <%= @author.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @author.gender %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', author_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyOpossum</title>
  <link type="text/css" rel="stylesheet" href="http://meyerweb.com/eric/tools/css/reset/reset.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <header class="global-header">
      <div class="global-header-title">
        Survey <img alt="Opossum" height="50" width="50" src="<%= asset_url("possum-icon.png")%>" class="possum-logo"> Opossum
      </div>
      <ul class="global-nav-container">
        <li class="global-nav-btn" id="my-survey-btn"><%= link_to "My Surveys", { controller: "session", action: "login" }, class: "global-nav-btn-link" %></li>
        <li class="global-nav-btn" id="survey-deisgner-btn"><%= link_to "Survey Designer", { controller: "surveys", action: "new" }, class: "global-nav-btn-link" %></li>
        <% if session[:author_id] %>
          <li class="global-nav-btn" id="profile-btn">
            <%= link_to_if(session[:author_id] != nil, "Profile", { controller: "authors", action: "show", id: session[:author_id] }, class: "global-nav-btn-link")  %></li>
        <% else %>
          <li class="global-nav-btn" id="my-survey-btn"><%= link_to "Profile", { controller: "session", action: "signup" }, class: "global-nav-btn-link" %></li>
        <% end %>
        <li class="global-nav-btn" id="support-btn"><a href="#" class="global-nav-btn-link">Support</a></li>
        <% if session[:author_id] %>
          <li class="global-nav-btn" id="profile-btn">
            <%= link_to_if(session[:author_id] != nil, "Logout", { controller: "session", action: "logout" }, class: "global-nav-btn-link")  %></li>
        <% else %>
          <li class="global-nav-btn" id="my-survey-btn"><%= link_to "Logout", { controller: "session", action: "login" }, class: "global-nav-btn-link" %></li>
        <% end %>
      </ul>
    </header>

    <%= yield %>

    <footer class="global-footer-container" id="">
      <div class="global-footer-top">
<div class="global-footer-top-wrapper">
        <div class="global-footer-product-container">
          <div class="global-footer-product-title">
            Product
          </div>
          <div class="global-footer-product">
            <%= link_to "My Surveys", { controller: "session", action: "login" } %>
          </div>
          <div class="global-footer-product">
            <%= link_to "Survey Designer", { controller: "surveys", action: "new" } %>
          </div>
          <div class="global-footer-product">
            <% if session[:author_id] %>
              <%= link_to "Profile", { controller: "authors", action: "show", id: session[:author_id] } %>
            <% else %>
              <%= link_to "Profile", { controller: "session", action: "signup" } %>
            <% end %>
          </div>
          <div class="global-footer-product">
            <a href="#">Support</a>
          </div>
          <div class="global-footer-product">
            <% if session[:author_id] %>
              <%= link_to "Logout", { controller: "session", action: "logout" } %>
            <% else %>
              <%= link_to "Logout", { controller: "session", action: "login" } %>
            <% end %>
          </div>
        </div> <!--End global-footer-product-->
        <div class="global-footer-company-container">
          <div class="global-footer-company-title">
            Company
          </div>
          <div class="global-footer-company">
            <a href="#">About Us</a>
          </div>
          <div class="global-footer-company">
            <a href="#">Blog</a>
          </div>
          <div class="global-footer-company">
            <a href="#">Jobs</a>
          </div>
          <div class="global-footer-company">
            <a href="#">Contact Us</a>
          </div>
        </div>  <!--End global-footer-company-->
        <div class="global-footer-connect-container">
          <div class="global-footer-connect-title">
            Connect
          </div>
          <div class="global-footer-connect">
            <a href="https://twitter.com?lang=en"><i class="fa fa-twitter"></i></a>
          </div>
          <div class="global-footer-connect">
            <a href="https://www.linkedin.com"><i class="fa fa-linkedin"></i></a>
          </div>
          <div class="global-footer-connect">
            <a href="https://www.facebook.com"><i class="fa fa-facebook"></i></a>
          </div>
          <div class="global-footer-connect">
            <a href="https://plus.google.com"><i class="fa fa-google-plus"></i></a>
          </div>
        </div>  <!--End global-footer-connect-->
</div>
      </div>
      <div class="sub-global-footer">
        <div class="sub-global-footer-teamname">Team: &nbsp; You Got Surved</div>
        <div class="sub-global-footer-team">
          <div class="sub-global-footer-teammembers">Members:</div>
          <div class="sub-global-footer-teammembers">Marcia Corprew</div>
          <div class="sub-global-footer-teammembers">Joseph DePompeis</div>
          <div class="sub-global-footer-teammembers">Andrew Baron</div>
          <div class="sub-global-footer-teammembers">Dennis Goldin</div>
        </div>
      </div> <!--End sub-global-footer -->
    </footer>

  </body>
</html>

app/views/session/login.html.erb
<%= form_tag(session_login_path) do %>

<div class="login-page-wrapper">

  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>

  <div class="login-page-login-box">
    <div class="login-box-header">
      Log In
    </div>
    <div class="login-box-input-wrapper">

  <p class="login-box-user-id" ><%= label_tag :name %>
  <%= text_field_tag :name %></p>

  <p class="login-box-user-password"><%= label_tag :password %>
  <%= password_field_tag :password %></p>

  <%= submit_tag "Log in", class: "login-box-login-btn" %>


<%= link_to 'Sign Up', new_author_path, class: "login-box-login-btn" %>

<% end %>

  </div>
</div>
</div>

app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>

app/views/session/signup.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>Create Your Account</h1>

<%= form_tag(session_signup_path) do %>

  <p><%= label_tag :name %>
  <%= text_field_tag :name %></p>

  <p><%= label_tag :password %>
  <%= password_field_tag :password %></p>

  <%= submit_tag "Sign Up" %>
<% end %>

app/views/surveys/_form.html.erb
<div class="survey-designer-wrapper">

  <div class="survey-designer-title">
    Survey Designer
  </div>
  <div class="survey-designer-survey-wrapper">

<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="survey-designer-survey-title-description">
    <div class="survey-title-label">
      <%= f.label :title %><br>
    </div>
    <div class="new-survey-title">
      <%= f.text_field :title %>
    </div>
    <div class="survey-description-label">
      <%= f.label :description %><br>
    </div>
    <div class="new-survey-description">
      <%= f.text_area :description %>
    </div>
  </div>

  <% if @survey.id %>

    <div class="field">
      <%= f.label :link %><br>
    </div>
    <div class="field">
      <%= f.text_field :link, :value => url_for( :controller => 'surveys', :action => 'take', :only_path => false ), :readonly => true, :size => 50 %>
    </div>
  <% end %>
  <% f.label :author_id %><br>
  <%= f.hidden_field :author_id, :value => session[:author_id] %>

  <h3> Questions </h3>
    <% if params[:action] == "new" %>
    <%= f.fields_for :questions do |ff| %>
    <div>
      <%= ff.label :text %>
      <%= ff.text_field :text, placeholder: "Your Question" %>
      <%= ff.label :order_number %>
      <%= ff.text_field :order_number, placeholder: "Order Number"  %>
      <%= ff.label :question_type %>
      <%= ff.select :question_type, [['YesNo', 'YesNo' ], ['ShortAnswer', 'ShortAnswer'], ['LongAnswer', 'LongAnswer']] %>
      Required? <%= ff.check_box :required %>
      <%= ff.hidden_field :survey_id, :value => @survey.id%>
    <% end %>
    </div>

    <% else %>
    <%= f.fields_for :questions, f.object.questions.order(:order_number) do |ff| %>

    <div>
      <%= ff.label :text %>
      <%= ff.text_field :text, placeholder: "Your Question" %>
      <%= ff.label :order_number %>
      <%= ff.text_field :order_number, placeholder: "Order Number"  %>
      <%= ff.label :question_type %>
      <%= ff.select :question_type, [['YesNo', 'YesNo' ], ['ShortAnswer', 'ShortAnswer'], ['LongAnswer', 'LongAnswer']] %>
      Required? <%= ff.check_box :required %>
      Delete? <%= ff.check_box :obliterate %>
      <%= ff.hidden_field :survey_id, :value => @survey.id%>
    <% end %>
    </div>

    <% end %>
    <input type="submit" name="add-question-btn" value="Add Question" id="add-question-btn" class="survey-designer-add-question-btn">


  <div class="survey-designer-btn-wrapper actions">
    <%= f.submit 'Create Survey', :class => 'survey-designer-save-btn actions'%>

  </div>

<% end %>

 </div>
</div>

app/views/surveys/_take_form.html.erb
<%= form_for @survey,  url: {action: "store"} do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= @survey.title %></p>
  </div>
  <div class="field">
    <p><%= f.label :description %>:
    <%= @survey.description %>
  </div>

  <% f.label :author_id %><br>
  <%= f.hidden_field :author_id, :value => session[:author_id] %>

  <h3> Questions </h3>
  <h4> Questions marked with an '*' are required. </h4>
  <ol>

    <%= f.fields_for :questions, f.object.questions.order(:order_number) do |ff| %>
      <%= ff.fields_for :answers, ff.object.answers.build do |fff| %>
      <li>
        <div>
          <%=ff.object.text%> <% if ff.object.required %> * <%end%><br>
          <% if ff.object.question_type == "YesNo" %>
            Answer <%= fff.radio_button(:text, "Yes") %> <%= label_tag(:text_yes, "Yes") %>
            <%= fff.radio_button(:text, "No") %> <%= label_tag(:text_no, "No") %>
            <%= fff.hidden_field :taker_id, :value => @taker.id%>
          <% elsif ff.object.question_type == "ShortAnswer" %>
            Answer <%= fff.label :text %>
            <%= fff.text_field :text %>
            <%= fff.hidden_field :taker_id, :value => @taker.id%>
          <% else %>
            Answer <%= fff.label :text %>
            <%= fff.text_area :text, size: "24x6" %>
            <%= fff.hidden_field :taker_id, :value => @taker.id%>
          <% end %>



        </div>
      </li>
      <% end %>
    <% end %>
  </ol>
  <div class="actions">
    <%= f.submit "COMPLETE SURVEY" %>
  </div>

<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<div class="my-surveys-survey-wrapper">

<p id="notice"><%= notice %></p>

<h1 class="my-surveys-title">My Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Link</th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody >
    <% @surveys.each do |survey| %>
      <tr>
        <td class="my-surveys-survey"><%= survey.title %></td>
        <td class="my-surveys-survey"><%= survey.description %></td>
        <td class="my-surveys-survey"><%= survey.link %></td>
        <td class="my-surveys-btn"><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td class="my-surveys-btn"><%= link_to 'Take', action: "take", id: survey.id %></td>
        <td class="my-surveys-btn"><%= link_to 'Results', action: "results", id: survey.id %></td>
        <td class="my-surveys-btn">><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>


</div>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>


<%= link_to 'Back', surveys_path %>

app/views/surveys/results.html.erb
<h1> Survey  Information</h1>
<p>
  <strong>Title:</strong>
  <%= @survey.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @survey.author_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @survey.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @survey.link %>
</p>


<h1> Survey Questions</h1>
<br>
<% @survey.questions.order(:order_number).each do |question| %>
  <p><strong>Question Order Number:</strong>
  <%= question.order_number %> </p>
  <p><strong>Question Text:</strong>
  <%= question.text %></p>
  <p><strong>Question Was Required:</strong>
  <%= question.required ? question.required : "false"  %></p>
  <br>
  <% question.answers.each do |question_response| %>
    <p>User #<%= question_response.taker_id %> Response: <%= question_response.text %></p>
    <p></p>
    <br>
  <% end %>

<% end %>


<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @survey.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @survey.author_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @survey.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @survey.link %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/take.html.erb
<h1>Take Survey</h1>

<%= render 'take_form' %>

<%= link_to 'Back', surveys_path %>